### ISSUE TITLE
How to start sails console?

### ISSUE THREAD

**Issue by bossyang** [ghaiklor/generator-sails-rest-api#152]
I know it's because of babel but what is the correct way?
````
$ sails console
api-demo/config/blueprints.js:12
export default {
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:414:25)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
````

**Comment by ghaiklor** [comment]
@bossyang try to add `console` script in `package.json`

```
"console": "babel-node ./node_modules/.bin/sails console"
```

Then run `npm run console`.

**Comment by bossyang** [comment]
@ghaiklor Thanks. It works!
