### ISSUE TITLE
Error after npm start - TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by mrcarl79** [ghaiklor/generator-sails-rest-api#173]
Hi,

I'm getting an error starting this, does this log mean anything to you?? I believe I've done all that was needed..

Thanks, Carl

Carls-iMac:demo-sails-rest-api carl$ npm start

> demo-sails-rest-api@0.1.0 start /Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api
> node app.js

path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.posix.resolve (path.js:426:5)
    at Function.sync (/Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/node_modules/sails-service-storage/node_modules/mkdirp/index.js:68:14)
    at LocalStorage.createUploadsFolder (/Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/node_modules/sails-service-storage/lib/LocalStorage.js:59:27)
    at new LocalStorage (/Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/node_modules/sails-service-storage/lib/LocalStorage.js:46:10)
    at exports.default (/Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/node_modules/sails-service-storage/lib/index.js:31:12)
    at Object.<anonymous> (/Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/api/services/StorageService.js:4:16)
    at Module._compile (module.js:425:26)
    at normalLoader (/Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/node_modules/include-all/index.js:44:9)
    at buildDictionary (/Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.optional (/Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/node_modules/sails-build-dictionary/index.js:160:9)
    at Hook.loadServices (/Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/node_modules/sails/lib/hooks/moduleloader/index.js:310:23)
    at Hook.bound [as loadServices] (/Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Hook.loadModules (/Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/node_modules/sails/lib/hooks/services/index.js:35:18)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! demo-sails-rest-api@0.1.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the demo-sails-rest-api@0.1.0 start script 'node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the demo-sails-rest-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls demo-sails-rest-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/carl/Development/Clients/Test/Repository/master/demo-sails-rest-api/npm-debug.log

**Comment by ghaiklor** [comment]
@mrcarl79 Did generator itself create the project successfully? Maybe some warnings, errors...
Also provide your environment information (node version, npm, yeoman and generator)

**Comment by fuadhasni** [comment]
**This is just for any noob like me visiting this issue for seeking solution, I came across the same issue**

The error is shown if you have selected Local Storage service and the you have not provided the following in your `.\config\services\storage.js` file.

` provider: {
        uploads: path.resolve(__dirname, '../uploads')
      }`

so, basically it is about providing a directory to save files to your local storage.

Full code of the  `.\config\services\storage.js` file should be as follows, 
`const path = require('path');
module.exports = {
 services: {
    storage: {
      provider: {
        uploads: path.resolve(__dirname, '../uploads')
      }
    }
  }
}`
