### ISSUE TITLE
npm start failed:

### ISSUE THREAD

**Issue by davidxiao** [ghaiklor/generator-sails-rest-api#185]
[vagrant@localhost test02]$ npm start
> sails-rest-api@0.1.0 start /vagrant/sailjs/test02
> node app.js
module.js:338
    throw err;
    ^
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/vagrant/sailjs/test02/api/hooks/swagger/index.js:6:30)
    at Module._compile (module.js:434:26)
    at normalLoader (/vagrant/sailjs/test02/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:200:5)
    at Object.require.extensions.(anonymous function) [as .js] (/vagrant/sailjs/test02/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:217:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /vagrant/sailjs/test02/node_modules/sails/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/vagrant/sailjs/test02/node_modules/sails/node_modules/include-all/index.js:44:9)
    at /vagrant/sailjs/test02/node_modules/sails/node_modules/include-all/index.js:54:23

**Comment by davidxiao** [comment]
Fixed by installing express, which seems required in hook for swagger?
need to add express module in project root's package.json
