### ISSUE TITLE
yo raises exception

### ISSUE THREAD

**Issue by Clan-Utility** [ghaiklor/generator-sails-rest-api#188]
MacOS 10.10.4
Node v.0.12.7
yo v1.4.8
generator-sails-rest-api v.1.1.0

After answering project name, it raises exceptions

Application questions:
? Application name aProject
/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/rx-lite/rx.lite.js:75
    throw e;
          ^
TypeError: undefined is not a function
    at /usr/local/lib/node_modules/generator-sails-rest-api/generators/app/steps/prompting.js:28:28
    at AppGenerator.<anonymous> (/usr/local/lib/node_modules/generator-sails-rest-api/node_modules/yeoman-generator/lib/base.js:234:7)
    at PromptUI.onCompletion (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/inquirer/lib/ui/prompt.js:57:10)
    at AnonymousObserver.Rx.AnonymousObserver.AnonymousObserver.completed (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/rx-lite/rx.lite.js:1550:12)
    at AnonymousObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/rx-lite/rx.lite.js:1489:14)
    at Subject.Rx.Subject.addProperties.onCompleted (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/rx-lite/rx.lite.js:5871:19)
    at Subject.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/rx-lite/rx.lite.js:63:31)
    at AutoDetachObserverPrototype.completed (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/rx-lite/rx.lite.js:5796:56)
    at AutoDetachObserver.Rx.internals.AbstractObserver.AbstractObserver.onCompleted (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/rx-lite/rx.lite.js:1489:14)
    at AutoDetachObserver.tryCatcher (/usr/local/lib/node_modules/yo/node_modules/yeoman-environment/node_modules/rx-lite/rx.lite.js:63:31)

yo is working for other generators

**Comment by ghaiklor** [comment]
@Clan-Utility I saw this error before. Try to update global dependencies via `sudo npm -g update` or `sudo npm -g install yo generator-sails-rest-api`.

**Comment by Clan-Utility** [comment]
After updating to node v4.2.4, the problem is solved.
