### ISSUE TITLE
lodash 4.0.0 breaks things

### ISSUE THREAD

**Issue by fullstackwebdev** [ghaiklor/generator-sails-rest-api#192]
## kaboom!
```
└─[$]> npm start

> sails-rest-api@0.1.0 start /home/nuc/dev/sails
> node app.js

verbose: logger hook loaded successfully.
verbose: request hook loaded successfully.
verbose: Loading the app's models and adapters...
verbose: Loading app models...
verbose: Loading app adapters...
verbose: Loading blueprint middleware...
/home/nuc/dev/sails/node_modules/lodash/lodash.js:4389
        throw new TypeError(FUNC_ERROR_TEXT);
        ^

TypeError: Expected a function
    at createWrapper (/home/nuc/dev/sails/node_modules/lodash/lodash.js:4389:15)
    at Function.<anonymous> (/home/nuc/dev/sails/node_modules/lodash/lodash.js:8789:14)
    at Function.partial (/home/nuc/dev/sails/node_modules/lodash/lodash.js:8892:31)
    at Object.<anonymous> (/home/nuc/dev/sails/api/blueprints/find.js:4:21)
    at Module._compile (module.js:398:26)
    at normalLoader (/home/nuc/dev/sails/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/nuc/dev/sails/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at /home/nuc/dev/sails/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/home/nuc/dev/sails/node_modules/include-all/index.js:44:9)
    at buildDictionary (/home/nuc/dev/sails/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.optional (/home/nuc/dev/sails/node_modules/sails-build-dictionary/index.js:160:9)

npm ERR! Linux 3.19.0-42-generic
npm ERR! argv "/home/nuc/.nvm/versions/node/v5.4.0/bin/node" "/home/nuc/.nvm/versions/node/v5.4.0/bin/npm" "start"
npm ERR! node v5.4.0
npm ERR! npm  v3.5.3
npm ERR! code ELIFECYCLE
npm ERR! sails-rest-api@0.1.0 start: `node app.js`
npm ERR! Exit status 1
```

Setting lodash v3 in packages.json fixes it.

**Comment by NikkiDreams** [comment]
I'm getting that too. Lodash 4.0 is a significant updatehttps://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings

Removed _.pluck in favor of _.map with iteratee shorthand
for example in API/Blueprints/find.js and findone.js change _.pluck to _.map
This fixes the problem. 
_.pluck is used in a bunch of places so they will all have to get changed.

**Comment by ghaiklor** [comment]
@fullstackwebdev @NikkiDreams strange, I didn't upgrade lodash version. Did you install it from npm@latest or from `dev` branch ?

**Comment by NikkiDreams** [comment]
Yeah the latest gets installed by the  yo script. I spent all of 5 minutes making the few changes necessary to use lodash 4. It's super easy. I only had to touch 4 or 5 files. _pluck and _unique were it I think.

**Comment by ghaiklor** [comment]
@NikkiDreams @fullstackwebdev guys, I've published new version. This version also rewritten entirely without Babel plus some fixes. Feel free to create an issue if something wouldn't work.
BTW, generator works only from NodeJS 4.x and higher now.
