### ISSUE TITLE
onPassportAuth being called twice after AuthController.signin

### ISSUE THREAD

**Issue by NikkiDreams** [ghaiklor/generator-sails-rest-api#195]
I've been trying to debug this all day. Even another dev I work with is perplexed. I am using the default code from the initial install via yo.
Steps:
POST to /api/auth/signin with correct credentials.
Passport local strategy is called.
onPassportAuth is triggered and I see the user object returned in the first pass.
But then it appears onPassportAuth is triggered a second time before a response is sent to the client and that is when it fails with an ERROR: [ReferenceError: req is not defined] undefined

I added some debug logging to capture the process. But I am completely stumped.
```
onPassportAuth(req, res, error, user, info) {
        if (error || !user) {
          sails.log.verbose("onPassportAuth: ERROR", error, info);
          return res.negotiate(error || info);
        }
        else if(req && req.body) {
          sails.log.verbose("onPassportAuth: req.body, user",req.body, user);
        }
        return res.ok({
          token: CipherService.jwt.encodeSync({id: user.id}),
          user: user
        });
      }
```
Here is the output:
```
verbose: _onLocalStrategyAuth q@a.com 000000 function verified(err, user, info) {
    if (err) { return self.error(err); }
    if (!user) { return self.fail(info); }
    self.success(user, info);
  }
verbose: onPassportAuth: req.body, user { email: 'q@a.com', password: '000000' } { worksheets: null,
  id: 1,
  username: 'q',
  password: '$2a$10$.b..zyNcNz8XJA.s0Xx5UOyjgbxboVcwYJjFT2GSw0T6Z4CsNg2..',
  email: 'q@a.com',
  firstName: '',
  lastName: '',
  photo: '',
  phone: null,
  socialProfiles: '{}',
  postalCode: null,
  ref: null,
  details: {},
  active: true,
  adminId: null,
  createdAt: '2016-01-20T06:02:09.000Z',
  updatedAt: '2016-01-20T06:02:09.000Z' }
verbose: onPassportAuth: ERROR ReferenceError: req is not defined
  at Object.exports.default (/www/5m/rest-api/api/responses/ok.js:23:15)
  at ServerResponse.bound [as ok] (/www/5m/rest-api/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
  at onPassportAuth (/www/5m/rest-api/config/passport.js:111:18)
  at apply (/www/5m/rest-api/node_modules/lodash/lodash.js:405:17)
  at wrapper (/www/5m/rest-api/node_modules/lodash/lodash.js:4254:16)
  at Strategy.strategy.success (/www/5m/rest-api/node_modules/passport/lib/middleware/authenticate.js:201:18)
  at verified (/www/5m/rest-api/node_modules/passport-local/lib/strategy.js:83:10)
  at /www/5m/rest-api/config/passport.js:70:12
  at tryCatcher (/www/5m/rest-api/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._settlePromiseFromHandler (/www/5m/rest-api/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
  at Promise._settlePromiseAt (/www/5m/rest-api/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
  at Promise._settlePromises (/www/5m/rest-api/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
  at Async._drainQueue (/www/5m/rest-api/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
  at Async._drainQueues (/www/5m/rest-api/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
  at Immediate.Async.drainQueues [as _onImmediate] (/www/5m/rest-api/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)
  at processImmediate [as _immediateCallback] (timers.js:383:17)
 [ReferenceError: req is not defined] undefined
```

**Comment by ghaiklor** [comment]
@NikkiDreams can you provide action `signin` from controller and node\npm versions as well?
And... `responses/ok.js` file too.

**Comment by NikkiDreams** [comment]
Yes. I will paste those in first thing in the morning.

**Comment by NikkiDreams** [comment]
○ → node --version
v4.2.4
○ → npm --version
3.5.2

```
/**
 * Sign in by email\password
 * @param req
 * @param res
 */
export function signin(req, res) {
  //{ user: { id: { email: 'f@f.com', password: '123456' } } }
  let data = req.body;
    if(data && data.user.auth){
      req.body = {};
      req.body['email'] = data.user.auth.email;
      req.body['password'] = data.user.auth.password;
    }
  sails.log.info("SIGNIN____");
  passport.authenticate('local', _.partial(sails.config.passport.onPassportAuth, req, res))(req, res);
}
```

Responses OK
```
/**
 * 200 (OK) Response
 *
 * General status code. Most common code used to indicate success.
 * The actual response will depend on the request method used.
 * In a GET request, the response will contain an entity corresponding to the requested resource.
 * In a POST request the response will contain an entity describing or containing the result of the action.
*/

import _ from 'lodash';

export default function (data, config) {
  let sails = req._sails;
  let response = _.assign({
    code: _.get(config, 'code', 'OK'),
    message: _.get(config, 'message', 'Operation is successfully executed'),
    data: data || {}
  }, _.get(config, 'root', {}));

  sails.log.silly('res.ok() :: Sending 200 ("OK") response');
  this.res.status(200);
  this.res.json(response);
}

/**
 * 200 (OK) Response
 *
 * Usage:
 * return res.ok();
 * return res.ok(data);
 * return res.ok(data, 'auth/login');
 *
 * @param  {Object} data
 * @param  {String|Object} options
 *          - pass string to render specified view
 */
/*
module.exports = function sendOK (data, options) {

  // Get access to `req`, `res`, & `sails`
  var req = this.req;
  var res = this.res;
  var sails = req._sails;

  sails.log.silly('res.ok() :: Sending 200 ("OK") response');

  // Set status code
  res.status(200);

  // If appropriate, serve data as JSON(P)
  if (req.wantsJSON) {
    return res.jsonx(data);
  }

  // If second argument is a string, we take that to mean it refers to a view.
  // If it was omitted, use an empty object (`{}`)
  options = (typeof options === 'string') ? { view: options } : options || {};

  // If a view was provided in options, serve it.
  // Otherwise try to guess an appropriate view, or if that doesn't
  // work, just send JSON.
  if (options.view) {
    return res.view(options.view, { data: data });
  }

  // If no second argument provided, try to serve the implied view,
  // but fall back to sending JSON(P) if no view can be inferred.
  else return res.guessView({ data: data }, function couldNotGuessView () {
    return res.jsonx(data);
  });

};
*/


```

**Comment by NikkiDreams** [comment]
Oh gosh. I think I just found the problem. I have looked high and low for the little 'req'!
Line 13 of responses/ok.js
```
let sails = req._sails;
```
Debugging has been a bit difficult due to lack of a more meaningful stack-traces from Sails internals.I'm testing with changes now and will update this ticket later. 

BTW this project is the best thing that has happened to Sails in about 3 years!

**Comment by NikkiDreams** [comment]
Update: I tested signin and it appears to be working now. I do not know where the problem line of code came from. I do recall if it is part of the initial installation or not. Generally I have not had need to mess with the response files. 
Cheers

**Comment by ghaiklor** [comment]
@NikkiDreams I just looked into `responses/ok.js` in generator templates:

```js
export default function (data, config) {
  let response = _.assign({
    code: _.get(config, 'code', 'OK'),
    message: _.get(config, 'message', 'Operation is successfully executed'),
    data: data || {}
  }, _.get(config, 'root', {}));

  this.res.status(200);
  this.res.jsonx(response);
}
```

It different that yours that is strange.

**Comment by NikkiDreams** [comment]
I must have changed that file unknowingly or it was the result of merging the code in the older repo. If it's not in the default install then I guess we can call this one closed. User Error :-)
Thanks for checking

**Comment by ghaiklor** [comment]
@NikkiDreams I'll check it after Global Game Jam. BTW, I'm planning to rewrite Sails project generated by generator without Babel and support only for NodeJS 4.x and higher. I already did it to generator sources and going to make this in Sails project.
