### ISSUE TITLE
TypeError: cipher is not a function

### ISSUE THREAD

**Issue by CodeQueen5M** [ghaiklor/generator-sails-rest-api#200]
I am getting this with the latest release. The install is 100% out of the box with no changes. I found this when I set up a new project as a baseline reference.

/www/5m/sails-yo-gen/api/services/CipherService.js:7
  jwt: cipher('jwt', config.services.cipher.jwt)
       ^

TypeError: cipher is not a function
    at Object.<anonymous> (/www/5m/sails-yo-gen/api/services/CipherService.js:7:8)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at /www/5m/sails-yo-gen/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/www/5m/sails-yo-gen/node_modules/include-all/index.js:44:9)
    at buildDictionary (/www/5m/sails-yo-gen/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.optional (/www/5m/sails-yo-gen/node_modules/sails-build-dictionary/index.js:160:9)
    at Hook.loadServices (/www/5m/sails-yo-gen/node_modules/sails/lib/hooks/moduleloader/index.js:310:23)
    at Hook.bound [as loadServices] (/www/5m/sails-yo-gen/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Hook.loadModules (/www/5m/sails-yo-gen/node_modules/sails/lib/hooks/services/index.js:35:18)
    at Hook.bound [as loadModules] (/www/5m/sails-yo-gen/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)

**Comment by ghaiklor** [comment]
@CodeQueen5M I already fixed that in appropriate services, try to call `npm update`.
