### ISSUE TITLE
this.res is undefined in response functions

### ISSUE THREAD

**Issue by riyastk** [ghaiklor/generator-sails-rest-api#204]
Every request to the server shows Type Error. this.res is undefined in every response function
```
Unhandled rejection TypeError: Cannot read property 'serverError' of undefined
    at Object.module.exports.error (/home/riyas/mywork/test/autoparts-api/api/responses/negotiate.js:26:15)
    at bound (/home/riyas/mywork/test/autoparts-api/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at tryCatcher (/home/riyas/mywork/test/autoparts-api/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/riyas/mywork/test/autoparts-api/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/riyas/mywork/test/autoparts-api/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/riyas/mywork/test/autoparts-api/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/riyas/mywork/test/autoparts-api/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/riyas/mywork/test/autoparts-api/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/riyas/mywork/test/autoparts-api/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:384:17)

```

**Comment by ghaiklor** [comment]
@riyastk it's all because of migration to native ES6 support and removing Babel. I'll fix this in few minutes. Get in touch in this issue :+1:

**Comment by riyastk** [comment]
@ghaiklor  thanks. Waiting for your update

**Comment by ghaiklor** [comment]
@riyastk you can update generator and call `yo sails-rest-api:resonse --all` in your project folder. It will regenerate responses with fixes.
