### ISSUE TITLE
cannot find module express

### ISSUE THREAD

**Issue by prisonier** [ghaiklor/generator-sails-rest-api#212]
Hi,

After a fresh install and trying to lunch the app through node start or sails lift I get this error :  

```javascript
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/libre/dev/test/api/hooks/swagger/index.js:9:17)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)

    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at /home/libre/dev/test/node_modules/sails/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/home/libre/dev/test/node_modules/sails/node_modules/include-all/index.js:44:9)
    at /home/libre/dev/test/node_modules/sails/node_modules/include-all/index.js:54:23
    at Array.forEach (native)

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/home/libre/.nvm/versions/node/v4.3.1/bin/node" "/home/libre/.nvm/versions/node/v4.3.1/bin/npm" "start"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE
npm ERR! sails-rest-api@0.1.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sails-rest-api@0.1.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the sails-rest-api package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls sails-rest-api
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/libre/dev/test/npm-debug.log
```

I don't know if it is related to sails or to this generator.
Of course, I fixed it by running : 
```bash
npm install express --save
```

**Comment by ghaiklor** [comment]
It's related to npm 2 and 3. I can do nothing with that. So, yes, solution is to install it manually.

**Comment by prisonier** [comment]
Ok so this can be closed.

Maybe you should say it in readme ?
