### ISSUE TITLE
Facebook Login return Error

### ISSUE THREAD

**Issue by steveacalabro** [ghaiklor/generator-sails-rest-api#217]
I'm getting the following error when trying to get the Facebook Authentication to work.

`Unhandled rejection TypeError: Converting circular structure to JSON`

I have narrowed the issue down to the passport.js config file 

`const _onSocialStrategyAuth = (req, accessToken, refreshToken, profile, next) => {
  if (!req.user) {
    let criteria = {};
    criteria['socialProfiles.' + profile.provider + '.id'] = profile.id;

    let model = {
      username: profile.username || profile.displayName || '',
      email: (profile.emails[0] && profile.emails[0].value) || '',
      firstName: (profile.name && profile.name.givenName) || '',
      lastName: (profile.name && profile.name.familyName) || '',
      photo: (profile.photos[0] && profile.photos[0].value) || '',
      socialProfiles: {}
    };
    model.socialProfiles[profile.provider] = profile._json;

    User
      .findOrCreate(criteria, model)
      .then(user => {
        if (!user) return next(null, null, sails.config.errors.AUTH_FAILED);
        return next(null, user, {});
      })
      .catch(next);
    } else {
      req.user.socialProfiles[profile.provider] = profile._json;
      req.user.save(next);
    }
    };`

**Comment by ghaiklor** [comment]
@steveacalabro can you debug more 'cause I can't reproduce it.

**Comment by steveacalabro** [comment]
I've pretty much been able to narrow it down to something with the `User.findOrCreate()` line and below

Here's the strategy im using 
```
/**
 * Configuration object for social strategies
 * @type {Object}
 * @private
 */
const FACEBOOK_STRATEGY_CONFIG = {
  clientID: '<Removed this>',
  clientSecret: '<Removed this>',
  callbackURL: 'http://localhost:3000/v1/auth/social/callback',
  passReqToCallback:true
};
```

This is at the bottom
`passport.use(new FacebookTokenStrategy(_.assign({}, FACEBOOK_STRATEGY_CONFIG), _onSocialStrategyAuth));`



More extensive error

```
Unhandled rejection TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ServerResponse.res.json (/home/midevilworm/_git/myapp/api/node_modules/express/lib/response.js:231:19)
    at ServerResponse.jsonx (/home/midevilworm/_git/myapp/api/node_modules/sails/lib/hooks/responses/index.js:218:21)
    at Object.module.exports (/home/midevilworm/_git/myapp/api/api/responses/serverError.js:20:12)
    at ServerResponse.bound [as serverError] (/home/midevilworm/_git/myapp/api/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Object.module.exports (/home/midevilworm/_git/myapp/api/api/responses/negotiate.js:25:14)
    at ServerResponse.bound [as negotiate] (/home/midevilworm/_git/myapp/api/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at onPassportAuth (/home/midevilworm/_git/myapp/api/config/passport.js:166:38)
    at apply (/home/midevilworm/_git/myapp/api/node_modules/lodash/lodash.js:418:27)
    at wrapper (/home/midevilworm/_git/myapp/api/node_modules/lodash/lodash.js:4450:16)
    at FacebookTokenStrategy.strategy.error (/home/midevilworm/_git/myapp/api/node_modules/passport/lib/middleware/authenticate.js:340:18)
    at verified (/home/midevilworm/_git/myapp/api/node_modules/passport-facebook-token/lib/index.js:96:36)
    at tryCatcher (/home/midevilworm/_git/myapp/api/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/midevilworm/_git/myapp/api/node_modules/waterline/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/midevilworm/_git/myapp/api/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/midevilworm/_git/myapp/api/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/midevilworm/_git/myapp/api/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/midevilworm/_git/myapp/api/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/midevilworm/_git/myapp/api/node_modules/waterline/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

```

**Comment by ghaiklor** [comment]
@steveacalabro why did you set `callbackURL` ? There is no such things.

**Comment by steveacalabro** [comment]
@ghaiklor I set it because I was getting the error so I tried to look into what was missing from the passport docs and it was that

**Comment by ghaiklor** [comment]
@steveacalabro https://github.com/drudge/passport-facebook-token

**Comment by steveacalabro** [comment]
@ghaiklor When I review that it looks different than what the generator creates. Should I be doing the User.findOrCreate() that way?

**Comment by ghaiklor** [comment]
@steveacalabro you can try, I'm wondering what happens because you're the first one with that issue.

**Comment by steveacalabro** [comment]
@ghaiklor I think I was able to narrow it down farther. I'm using mySql, when I tried to convert the User.findOrCreate() function to the passport way I was still recieveing an error. When I starting picking it apart I was left with code that looked like the following.

```
User.findOne(criteria, function(err, user) {
      console.log("Gets to here");
      if (err) {
        console.log("Error");
        return next(err);
      }
});
```

Both "Gets to here" and "Error" are displayed to the console and then I get this error returned back to me. Which has me really confused.

```
/home/midevilworm/_git/myapp/api/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:77
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ServerResponse.res.json (/home/midevilworm/_git/myapp/api/node_modules/express/lib/response.js:231:19)
    at ServerResponse.jsonx (/home/midevilworm/_git/myapp/api/node_modules/sails/lib/hooks/responses/index.js:218:21)
    at Object.module.exports (/home/midevilworm/_git/myapp/api/api/responses/serverError.js:20:12)
    at ServerResponse.bound [as serverError] (/home/midevilworm/_git/myapp/api/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Object.module.exports (/home/midevilworm/_git/myapp/api/api/responses/negotiate.js:25:14)
    at ServerResponse.bound [as negotiate] (/home/midevilworm/_git/myapp/api/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at onPassportAuth (/home/midevilworm/_git/myapp/api/config/passport.js:197:38)
    at apply (/home/midevilworm/_git/myapp/api/node_modules/lodash/lodash.js:418:27)
    at wrapper (/home/midevilworm/_git/myapp/api/node_modules/lodash/lodash.js:4450:16)
    at FacebookTokenStrategy.strategy.error (/home/midevilworm/_git/myapp/api/node_modules/passport/lib/middleware/authenticate.js:340:18)
    at verified (/home/midevilworm/_git/myapp/api/node_modules/passport-facebook-token/lib/index.js:96:36)
    at /home/midevilworm/_git/myapp/api/config/passport.js:139:16
    at /home/midevilworm/_git/myapp/api/node_modules/waterline/lib/waterline/query/finders/basic.js:79:22
    at /home/midevilworm/_git/myapp/api/node_modules/waterline/lib/waterline/query/finders/operations.js:71:20
    at wrapper (/home/midevilworm/_git/myapp/api/node_modules/waterline/node_modules/lodash/index.js:3602:19)
    at applyInOriginalCtx (/home/midevilworm/_git/myapp/api/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/home/midevilworm/_git/myapp/api/node_modules/waterline/lib/waterline/utils/normalize.js:331:16)
    at callback.error (/home/midevilworm/_git/myapp/api/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
    at _switch (/home/midevilworm/_git/myapp/api/node_modules/waterline/node_modules/switchback/lib/factory.js:56:28)
    at /home/midevilworm/_git/myapp/api/node_modules/waterline/lib/waterline/adapter/dql.js:164:26
    at wrapper (/home/midevilworm/_git/myapp/api/node_modules/waterline/node_modules/lodash/index.js:3602:19)

```

**Comment by steveacalabro** [comment]
@ghaiklor After some debugging I have found a few errors that deal with mysql. Could it be because of that?

**Comment by ghaiklor** [comment]
@steveacalabro change adapter to sails-mongo and check if it works. If so then issue with sails-mysql adapter.

**Comment by steveacalabro** [comment]
@ghaiklor Still gave the error about circular JSON

**Comment by steveacalabro** [comment]
@ghaiklor after some debugging it does look like its something with the sails-mysql. Thanks for the help. I'll bring the issue over there and see what they say
