### ISSUE TITLE
An error on "npm start"

### ISSUE THREAD

**Issue by alekor** [ghaiklor/generator-sails-rest-api#230]
Both for **Windows 7 + npm -v 3.0.6 + node -v 4.2.4** and **mac + npm -v 3.8.3 + node -v 5.8.0**
when execute "npm start"

**on Windows ->**
```
path.js:8
    throw new TypeError('Path must be a string. Received ' +
    ^

TypeError: Path must be a string. Received undefined
    at assertPath (path.js:8:11)
    at Object.win32.resolve (path.js:130:5)
    at Function.sync (D:\envatoServer\node_modules\mkdirp\index.js:68:14)
    at LocalStorage.createUploadsFolder (D:\envatoServer\node_modules\sails-serv
ice-storage\lib\LocalStorage.js:56:24)
    at new LocalStorage (D:\envatoServer\node_modules\sails-service-storage\lib\
LocalStorage.js:42:11)
    at exports.default (D:\envatoServer\node_modules\sails-service-storage\lib\i
ndex.js:9:12)
    at Object.<anonymous> (D:\envatoServer\api\services\StorageService.js:6:18)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at D:\envatoServer\node_modules\include-all\index.js:129:29
    at Array.forEach (native)
    at requireAll (D:\envatoServer\node_modules\include-all\index.js:44:9)

```

**on mac ->**
```

path.js:7
throw new TypeError('Path must be a string. Received ' + inspect(path));
^

TypeError: Path must be a string. Received undefined
at assertPath (path.js:7:11)
at Object.resolve (path.js:1186:7)
at Function.sync (/Users/korin/Documents/myDev/envatoServer/node_modules/sails-service-storage/node_modules/mkdirp/index.js:68:14)
at LocalStorage.createUploadsFolder (/Users/korin/Documents/myDev/envatoServer/node_modules/sails-service-storage/lib/LocalStorage.js:56:24)
at new LocalStorage (/Users/korin/Documents/myDev/envatoServer/node_modules/sails-service-storage/lib/LocalStorage.js:42:11)
at exports.default (/Users/korin/Documents/myDev/envatoServer/node_modules/sails-service-storage/lib/index.js:9:12)
at Object.<anonymous> (/Users/korin/Documents/myDev/envatoServer/api/services/StorageService.js:6:18)
at Module._compile (module.js:413:34)
at Object.Module._extensions..js (module.js:422:10)
at Module.load (module.js:357:32)
at Function.Module._load (module.js:314:12)
at Module.require (module.js:367:17)
at require (internal/module.js:16:19)
at /Users/korin/Documents/myDev/envatoServer/node_modules/sails/node_modules/include-all/index.js:129:29
at Array.forEach (native)
at requireAll (/Users/korin/Documents/myDev/envatoServer/node_modules/sails/node_modules/include-all/index.js:44:9)
```

**Comment by alekor** [comment]
Disregard this issue. Setup of the path for storage service was needed
