### ISSUE TITLE
call a bad parameter in a find request cause server to not send response to client

### ISSUE THREAD

**Issue by l1br3** [ghaiklor/generator-sails-rest-api#237]
Hi, if I have a 'channel' model and if I try to use the find blueprint : 

`http://localhost/v1/channels?limi=200` -> note the error 'limi' instead of 'limit'

I get this error and no response is sent to the client : 

```javascript
serverError :
Error (undefined) :: undefined
: ER_BAD_FIELD_ERROR: Unknown column 'channel.limi' in 'where clause'
    at Query.Sequence._packetToError (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)

    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)
    --------------------
    at Protocol._enqueue (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at PoolConnection.query (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:201:25)
    at __FIND__ (/home/libre/dev/facetube/node_modules/sails-mysql/lib/adapter.js:838:20)
    at afterwards (/home/libre/dev/facetube/node_modules/sails-mysql/lib/connections/spawn.js:84:5)
    at /home/libre/dev/facetube/node_modules/sails-mysql/lib/connections/spawn.js:40:7
    at Ping.onOperationComplete [as _callback] (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:99:5)
    at Ping.Sequence.end (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Ping.Sequence.OkPacket (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (/home/libre/dev/facetube/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at readableAddChunk (_stream_readable.js:153:18)
    at Socket.Readable.push (_stream_readable.js:111:10)
    at TCP.onread (net.js:531:20)

Details:  Error: ER_BAD_FIELD_ERROR: Unknown column 'channel.limi' in 'where clause'

Unhandled rejection TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at ServerResponse.res.json (/home/libre/dev/facetube/node_modules/sails/node_modules/express/lib/response.js:231:19)

    at ServerResponse.jsonx (/home/libre/dev/facetube/node_modules/sails/lib/hooks/responses/index.js:218:21)
    at Object.module.exports (/home/libre/dev/facetube/api/responses/serverError.js:22:12)
    at ServerResponse.bound [as serverError] (/home/libre/dev/facetube/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at Object.module.exports (/home/libre/dev/facetube/api/responses/negotiate.js:25:14)
    at bound (/home/libre/dev/facetube/node_modules/sails/node_modules/lodash/dist/lodash.js:729:21)
    at tryCatcher (/home/libre/dev/facetube/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/libre/dev/facetube/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/main/promise.js
:503:31)
    at Promise._settlePromiseAt (/home/libre/dev/facetube/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/main/promise.js:577:18)
    at Promise._settlePromises (/home/libre/dev/facetube/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/main/promise.js:693:14)
    at Async._drainQueue (/home/libre/dev/facetube/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/libre/dev/facetube/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/libre/dev/facetube/node_modules/sails/node_modules/waterline/node_modules/bluebird/js/mai
n/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)
```

I guess that should be handled. Maybe more related to sails instead of your module ? But as you overwritten some blueprints I'm not sure.

**Comment by ghaiklor** [comment]
@prisonier error specific for sails-mysql and waterline. Actually, Waterline emits this error, so you can try\catch, but I believe it should handles in Sails.

**Comment by prisonier** [comment]
Thanks for your answer but where should I try/catch ? In the find blueprint ? 
It would be better to have all waterline errors catched in the blueprints instead of relying on waterline to send proper errors.

**Comment by ghaiklor** [comment]
@prisonier yes, try to add try\catch in `find` blueprint.

**Comment by ghaiklor** [comment]
Closing due this issue is related to specific adapter, not the generator itself.
