### ISSUE TITLE
Blueprints.js ignored?

### ISSUE THREAD

**Issue by komocode** [ghaiklor/generator-sails-rest-api#269]
Here's my blueprints.js

```
export default {
  blueprints: {
    /**
     * When enabled, GET, POST, PUT and DELETE routes will be generated for everyone of a controller's actions
     * @type {Boolean}
     */
    actions: false,

    /**
     * When enabled, `index` action will be default action
     * @type {Boolean}
     */
    index: false,

    /**
     * REST blueprints are the automatically generated routes Sails uses to expose a conventional REST API
     * on top of a controller's `find`, `findOne`, `create`, `update`, and `destroy` actions
     * @type {Boolean}
     */
    rest: false,

    /**
     * Shortcut routes are simple helpers to provide access to a controller's CRUD methods from your browser's URL bar
     * @type {Boolean}
     */
    shortcuts: false,

    /**
     * An optional mount path for all blueprint routes on a controller, including `rest`, `actions`, and `shortcuts`
     * @type {String}
     */
    prefix: '',

    /**
     * An optional mount path for all blueprint routes on a controller, including only `rest`
     * @type {String}
     */
    restPrefix: '',

    /**
     * Whether to pluralize controller names in blueprint routes
     * @type {Boolean}
     */
    pluralize: false,

    /**
     * Whether the blueprint controllers should populate model fetches with data
     * from other models which are linked by associations
     * @type {Boolean}
     */
    populate: false,

    /**
     * Whether to run Model.watch() in the find and findOne blueprint actions
     * @type {Boolean}
     */
    autoWatch: false,

    /**
     * The default number of records to show in the response from a "find" action
     * @type {Number}
     */
    defaultLimit: 1000
  }
}
```

And I've commented out all routes relating to "workshops" in my routes.js folder

```
        'DELETE /api/admins/:id' : 'AdminController.deleteAdmin',

        // 'GET /api/workshops' : {blueprint:'find', model:'workshop'},
        // 'GET /api/workshops/:id' : {blueprint:'findone', model:'workshop'},
        // 'GET /api/workshops/nearby':'SearchController.workshopSearch',
        // 'PUT /api/workshops/:id' : 'AdminController.updateWorkshop',
        // 'POST /api/workshops' : {blueprint:'create', model:'workshop', policy:'isAuthenticated'},

        'POST /api/users' : 'UserController.signUp',
        'PUT /api/users/me' : 'UserController.updatePofile',

        'POST /api/:id/testauth' : 'PingController.testAuth',
        'GET /api/ping' : 'PingController.index',

        // 'POST /api/workshops/attendance' : 'WorkshopController.signUpWorkshop',
        'GET /api/users/me/attendance' : 'WorkshopController.getSignedUpWorkshops',

        // 'PUT /api/workshops/:id/likes' : 'WorkshopController.like',
        'PUT /api/topics/:id/likes' : 'TopicController.like',
```

But when I do a GET request: /api/workshops/nearby?lat=13.725777&lng=100.541065&distance=11.408501

Sails.js attempts to do some action that causes a circular dependency error
```
Error (undefined) :: undefined
app-0 : ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
app-0     at Query.Sequence._packetToError (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
app-0     at Query.ErrorPacket (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
app-0     at Protocol._parsePacket (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
app-0     at Parser.write (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
app-0     at Protocol.write (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
app-0     at Socket.<anonymous> (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
app-0     at emitOne (events.js:96:13)
app-0     at Socket.emit (events.js:188:7)
app-0     at readableAddChunk (_stream_readable.js:172:18)
app-0     at Socket.Readable.push (_stream_readable.js:130:10)
app-0     at TCP.onread (net.js:542:20)
app-0     --------------------
app-0     at Protocol._enqueue (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:141:48)
app-0     at PoolConnection.query (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:201:25)
app-0     at __FIND__ (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/lib/adapter.js:932:20)
app-0     at afterwards (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/lib/connections/spawn.js:84:5)
app-0     at /Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/lib/connections/spawn.js:40:7
app-0     at Ping.onOperationComplete [as _callback] (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/Pool.js:99:5)
app-0     at Ping.Sequence.end (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
app-0     at Ping.Sequence.OkPacket (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
app-0     at Protocol._parsePacket (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
app-0     at Parser.write (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
app-0     at Protocol.write (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
app-0     at Socket.<anonymous> (/Users/komocode/Desktop/technique-backend/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
app-0     at emitOne (events.js:96:13)
app-0     at Socket.emit (events.js:188:7)
app-0     at readableAddChunk (_stream_readable.js:172:18)
app-0     at Socket.Readable.push (_stream_readable.js:130:10)
app-0     at TCP.onread (net.js:542:20)
app-0 Details:  Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
app-0 Unhandled rejection TypeError: Converting circular structure to JSON
app-0     at Object.stringify (native)
app-0     at ServerResponse.res.json (/Users/komocode/Desktop/technique-backend/node_modules/express/lib/response.js:231:19)
app-0     at ServerResponse.jsonx (/Users/komocode/Desktop/technique-backend/node_modules/sails/lib/hooks/responses/index.js:222:21)
app-0     at Object.exports.default (/Users/komocode/Desktop/technique-backend/api/responses/serverError.js:19:12)
app-0     at ServerResponse.wrapper [as serverError] (/Users/komocode/Desktop/technique-backend/node_modules/sails/node_modules/lodash/index.js:3095:19)
app-0     at Object.exports.default (/Users/komocode/Desktop/technique-backend/api/responses/negotiate.js:23:14)
app-0     at wrapper (/Users/komocode/Desktop/technique-backend/node_modules/sails/node_modules/lodash/index.js:3095:19)
app-0     at tryCatcher (/Users/komocode/Desktop/technique-backend/node_modules/waterline/node_modules/bluebird/js/release/util.js:11:23)
app-0     at Promise._settlePromiseFromHandler (/Users/komocode/Desktop/technique-backend/node_modules/waterline/node_modules/bluebird/js/release/promise.js:491:31)
app-0     at Promise._settlePromise (/Users/komocode/Desktop/technique-backend/node_modules/waterline/node_modules/bluebird/js/release/promise.js:548:18)
app-0     at Promise._settlePromise0 (/Users/komocode/Desktop/technique-backend/node_modules/waterline/node_modules/bluebird/js/release/promise.js:593:10)
app-0     at Promise._settlePromises (/Users/komocode/Desktop/technique-backend/node_modules/waterline/node_modules/bluebird/js/release/promise.js:672:18)
app-0     at Promise._reject (/Users/komocode/Desktop/technique-backend/node_modules/waterline/node_modules/bluebird/js/release/promise.js:636:18)
app-0     at Promise._settlePromise (/Users/komocode/Desktop/technique-backend/node_modules/waterline/node_modules/bluebird/js/release/promise.js:563:21)
app-0     at Promise._settlePromise0 (/Users/komocode/Desktop/technique-backend/node_modules/waterline/node_modules/bluebird/js/release/promise.js:593:10)
app-0     at Promise._settlePromises (/Users/komocode/Desktop/technique-backend/node_modules/waterline/node_modules/bluebird/js/release/promise.js:672:18)
app-0     at Promise._reject (/Users/komocode/Desktop/technique-backend/node_modules/waterline/node_modules/bluebird/js/release/promise.js:636:18)
app-0     at /Users/komocode/Desktop/technique-backend/node_modules/waterline/node_modules/bluebird/js/release/nodeback.js:40:21
app-0     at wrapper (/Users/komocode/Desktop/technique-backend/node_modules/waterline/node_modules/lodash/index.js:3592:19)
app-0     at applyInOriginalCtx (/Users/komocode/Desktop/technique-backend/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
app-0     at wrappedCallback (/Users/komocode/Desktop/technique-backend/node_modules/waterline/lib/waterline/utils/normalize.js:335:16)
app-0     at callback.error (/Users/komocode/Desktop/technique-backend/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
```
My expectation of what should happen when I do that GET request should return a "not found" error since no paths are defined and actions/rest are set to false in my blueprints.js.

Is there another file in this project where I need to edit to disable auto generated routes?

**Comment by komocode** [comment]
Nevermind. Looks like it's a routing issue.
