### ISSUE TITLE
Facebook userId is not found

### ISSUE THREAD

**Issue by rizr** [ghaiklor/generator-sails-rest-api#3]
~~~
api/services/social/Facebook.js:10
    if (!(options || options.userId || options.accessToken)) {
                            ^
TypeError: Cannot read property 'userId' of undefined
    at new Facebook (api/services/social/Facebook.js:10:29)
    at Object.<anonymous> (api/services/SocialService.js:3:18)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at node_modules/sails/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
~~~

**Comment by rizr** [comment]
in SocialFactory need to export  module.exports = SocialFactory; NOT module.exports = Facebook
