### ISSUE TITLE
self.defaults is not a function

### ISSUE THREAD

**Issue by aliemre** [ghaiklor/generator-sails-rest-api#326]
Hi. I am currently this having issue after installation.

```
/Users/{user}/Desktop/{project}/node_modules/sails/lib/app/configuration/load.js:136
            var implicitDefaults = self.defaults(overrides.appPath || process.cwd());
                                        ^

TypeError: self.defaults is not a function
    at Array.async.auto.mixinDefaults (/Users/{user}/Desktop/{project}/node_modules/sails/lib/app/configuration/load.js:136:41)
    at /Users/{user}/Desktop/{project}/node_modules/async/lib/async.js:484:38
    at _each (/Users/{user}/Desktop/{project}/node_modules/async/lib/async.js:46:13)
    at Object.async.auto (/Users/{user}/Desktop/{project}/node_modules/async/lib/async.js:455:9)
    at Array.loadConfig (/Users/{user}/Desktop/{project}/node_modules/sails/lib/app/configuration/load.js:35:11)
    at /Users/{user}/Desktop/{project}/node_modules/async/lib/async.js:484:38
    at _each (/Users/{user}/Desktop/{project}/node_modules/async/lib/async.js:46:13)
    at Object.async.auto (/Users/{user}/Desktop/{project}/node_modules/async/lib/async.js:455:9)
    at Sails.load (/Users/{user}/Desktop/{project}/node_modules/sails/lib/app/load.js:51:11)
    at Sails.wrapper [as load] (/Users/{user}/Desktop/{project}/node_modules/lodash/lodash.js:4968:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! {project}@0.1.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the {project}@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/{user}/.npm/_logs/2017-07-21T10_36_42_870Z-debug.log
```

Thanks for your help.

**Comment by ghaiklor** [comment]
#325
