### ISSUE TITLE
Error running on windows machine 

### ISSUE THREAD

**Issue by rkdaredevil** [ghaiklor/generator-sails-rest-api#327]
**var implicitDefaults = self.defaults(overrides.appPath || process.cwd());
                                        ^**

TypeError: self.defaults is not a function
    at Array.async.auto.mixinDefaults (E:\sails-pots\node_modules\sails\lib\app\configuration\load.js:136:41)
    at E:\sails-pots\node_modules\async\lib\async.js:484:38
    at _each (E:\sails-pots\node_modules\async\lib\async.js:46:13)
    at Object.async.auto (E:\sails-pots\node_modules\async\lib\async.js:455:9)
    at Array.loadConfig (E:\sails-pots\node_modules\sails\lib\app\configuration\load.js:35:11)
    at E:\sails-pots\node_modules\async\lib\async.js:484:38
    at _each (E:\sails-pots\node_modules\async\lib\async.js:46:13)
    at Object.async.auto (E:\sails-pots\node_modules\async\lib\async.js:455:9)
    at Sails.load (E:\sails-pots\node_modules\sails\lib\app\load.js:51:11)
    at Sails.wrapper [as load] (E:\sails-pots\node_modules\lodash\lodash.js:4968:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! pots@0.1.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pots@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Vivek Singh\AppData\Roaming\npm-cache\_logs\2017-07-25T09_36_17_411Z-debug.log

**Comment by ghaiklor** [comment]
#326
