### ISSUE TITLE
unable to get the sails api project up and running after generating the api base using the sails-rest-api

### ISSUE THREAD

**Issue by anilprasad** [ghaiklor/generator-sails-rest-api#349]
I have used only two of the services 

1. CipherService and 
2. HashService.js

Followed the following steps..

$ sudo npm install -g yo generator-sails-rest-api
$ mkdir myapi
$ cd myapi/
$ yo sails-rest-api
$ npm start

Environment: Environment ubuntu 14.04 LTS, 64 bit, Intel x86

After npm start, I am getting the following error...

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.5
3 info using node@v8.9.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle myapi@0.1.0~prestart: myapi@0.1.0
6 silly lifecycle myapi@0.1.0~prestart: no script for prestart, continuing
7 info lifecycle myapi@0.1.0~start: myapi@0.1.0
8 verbose lifecycle myapi@0.1.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle myapi@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home.....
10 verbose lifecycle myapi@0.1.0~start: CWD: /home/rhea/sailap/myapi
11 silly lifecycle myapi@0.1.0~start: Args: [ '-c', 'node app.js' ]
12 silly lifecycle myapi@0.1.0~start: Returned: code: 1  signal: null
13 info lifecycle myapi@0.1.0~start: Failed to exec start script
14 verbose stack Error: myapi@0.1.0 start: `node app.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid myapi@0.1.0
16 verbose cwd /home/rhea/sailap/myapi
17 error Linux 3.13.0-45-generic
18 error argv "/usr/bin/node" "/usr/local/bin/npm" "start"
19 error node v8.9.4
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error myapi@0.1.0 start: `node app.js`
22 error Exit status 1

**Comment by anilprasad** [comment]
npm version : 3.10.5
node version : v8.9.4

**Comment by ghaiklor** [comment]
@anilprasad I don't see any info about Sails or generators internals in the stack trace. Without additional information I can't help here.

**Comment by anilprasad** [comment]
@ghaiklor thank you for the prompt reply. I did not get any other trace details apart from the above npm log. is this something to do with es6? as I could see good amount of usage of arrow functions in the code.

**Comment by ghaiklor** [comment]
@anilprasad you are using node v8, so it's not the case, imho. I believe, there are some old issues in generator-sails-rest-api related to ignoring stack trace in messages. Could be that is the case...

Try to generatre without additional services (clean setup). What will be the effect?
