### ISSUE TITLE
Cannot find module 'passport'

### ISSUE THREAD

**Issue by strobelpierre** [ghaiklor/generator-sails-rest-api#350]
Good morning,
I think I have a problem with the dependencies.
Indeed, when I run an "npm start"' I get errors like "Local package.json exists, but node_modules missing, did you mean to install?" so I run npm install and once done I still have missing dependencies.
"Details:Error: Cannot find module'passport'".
Sincerely Pierre
Sorry about my English I'm French;)
NPM Start : 
`info: Starting app...

/home/pierre/lab/js/test/newtestsailsyeoman/node_modules/include-all/lib/help-include-all-sync.js:281
              throw e;
              ^

`include-all` attempted to `require(/home/pierre/lab/js/test/newtestsailsyeoman/config/passport.js)`, but an error occurred:: 
Details:Error: Cannot find module 'passport'
    at Function.Module._resolveFilename (module.js:543:15)
    at Function.Module._load (module.js:470:25)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/pierre/lab/js/test/newtestsailsyeoman/config/passport.js:9:18)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
    at /home/pierre/lab/js/test/newtestsailsyeoman/node_modules/include-all/lib/help-include-all-sync.js:271:33
    at Array.forEach (<anonymous>)
    at _recursivelyIncludeAll (/home/pierre/lab/js/test/newtestsailsyeoman/node_modules/include-all/lib/help-include-all-sync.js:174:11)
    at includeAll (/home/pierre/lab/js/test/newtestsailsyeoman/node_modules/include-all/lib/help-include-all-sync.js:292:5)
    at helpBuildDictionary (/home/pierre/lab/js/test/newtestsailsyeoman/node_modules/include-all/lib/help-build-dictionary.js:43:15)
    at Function.module.exports.aggregate (/home/pierre/lab/js/test/newtestsailsyeoman/node_modules/include-all/index.js:101:10)
    at Array.loadOtherConfigFiles (/home/pierre/lab/js/test/newtestsailsyeoman/node_modules/sails/lib/hooks/moduleloader/index.js:247:22)
    at /home/pierre/lab/js/test/newtestsailsyeoman/node_modules/async/lib/async.js:591:38
    at _arrayEach (/home/pierre/lab/js/test/newtestsailsyeoman/node_modules/async/lib/async.js:85:13)
    at Object.async.auto (/home/pierre/lab/js/test/newtestsailsyeoman/node_modules/async/lib/async.js:552:9)
`
.npm/_logs/2018-03-20T09_16_26_523Z-debug.log
`0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@5.7.1
3 info using node@v9.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle sails-rest-api@0.1.0~prestart: sails-rest-api@0.1.0
6 info lifecycle sails-rest-api@0.1.0~start: sails-rest-api@0.1.0
7 verbose lifecycle sails-rest-api@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle sails-rest-api@0.1.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/pierre/lab/js/test/newtestsailsyeoman/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle sails-rest-api@0.1.0~start: CWD: /home/pierre/lab/js/test/newtestsailsyeoman
10 silly lifecycle sails-rest-api@0.1.0~start: Args: [ '-c', 'node app.js' ]
11 silly lifecycle sails-rest-api@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle sails-rest-api@0.1.0~start: Failed to exec start script
13 verbose stack Error: sails-rest-api@0.1.0 start: `node app.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at EventEmitter.emit (events.js:180:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:180:13)
13 verbose stack     at maybeClose (internal/child_process.js:936:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid sails-rest-api@0.1.0
15 verbose cwd /home/pierre/lab/js/test/newtestsailsyeoman
16 verbose Linux 4.13.0-37-generic
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v9.8.0
19 verbose npm  v5.7.1
20 error code ELIFECYCLE
21 error errno 1
22 error sails-rest-api@0.1.0 start: `node app.js`
22 error Exit status 1
23 error Failed at the sails-rest-api@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
`

**Comment by jamestharpe** [comment]
Same here. Start a new project, run `npm install`, and get this error.

**Comment by ghaiklor** [comment]
looks like an issue with missing dependencies list in `package.json`. Just install all the required packages via `npm install`

**Comment by ChrizzDF** [comment]
After having the same error as @jamestharpe I added each missing dependency after another. At the end there were like ~15 additional dependencies I had to install, even though I didn't want to use things like Location, but still I had to install these dependencies for that.
After this was done, I'm getting the next error which is:
`TypeError: _.get is not a function`

Probably it's because I'm using Sails v1.0 - I don't know.
