### ISSUE TITLE
not able to run the api

### ISSUE THREAD

**Issue by ghost** [ghaiklor/generator-sails-rest-api#356]
TypeError: _.chain(...).keyBy is not a function
    at Object.getPathItem (E:\webauctionsplus fix\WebAuction Api v2\api\hooks\swagger\lib\xfmr.js:160:8)
    at _.mapValues.pathGroup (E:\webauctionsplus fix\WebAuction Api v2\api\hooks\swagger\lib\xfmr.js:126:26)
    at E:\webauctionsplus fix\WebAuction Api v2\node_modules\lodash\index.js:3395:24
    at E:\webauctionsplus fix\WebAuction Api v2\node_modules\lodash\index.js:3073:15
    at baseForOwn (E:\webauctionsplus fix\WebAuction Api v2\node_modules\lodash\index.js:2046:14)
    at Function.mapValues (E:\webauctionsplus fix\WebAuction Api v2\node_modules\lodash\index.js:3394:9)
    at Object.getPaths (E:\webauctionsplus fix\WebAuction Api v2\api\hooks\swagger\lib\xfmr.js:125:14)
    at Object.getSwagger (E:\webauctionsplus fix\WebAuction Api v2\api\hooks\swagger\lib\xfmr.js:32:26)
    at sails.after (E:\webauctionsplus fix\WebAuction Api v2\api\hooks\swagger\index.js:31:25)
    at E:\webauctionsplus fix\WebAuction Api v2\node_modules\sails\lib\app\private\after.js:91:14
    at E:\webauctionsplus fix\WebAuction Api v2\node_modules\async\lib\async.js:721:13
    at E:\webauctionsplus fix\WebAuction Api v2\node_modules\async\lib\async.js:52:16
    at done (E:\webauctionsplus fix\WebAuction Api v2\node_modules\async\lib\async.js:246:17)
    at E:\webauctionsplus fix\WebAuction Api v2\node_modules\async\lib\async.js:44:16
    at Sails.<anonymous> (E:\webauctionsplus fix\WebAuction Api v2\node_modules\async\lib\async.js:718:17)
    at Sails.<anonymous> (E:\webauctionsplus fix\WebAuction Api v2\node_modules\async\lib\async.js:167:37)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Sails.emit (events.js:208:7)
    at Sails.emitter.emit (E:\webauctionsplus fix\WebAuction Api v2\node_modules\sails\lib\app\private\after.js:50:11)
    at sailsReady (E:\webauctionsplus fix\WebAuction Api v2\node_modules\sails\lib\app\lift.js:53:11)
    at E:\webauctionsplus fix\WebAuction Api v2\node_modules\async\lib\async.js:721:13
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webauction-rest-api@0.1.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webauction-rest-api@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[2018-04-23T14_13_12_867Z-debug.log](https://github.com/ghaiklor/generator-sails-rest-api/files/1938572/2018-04-23T14_13_12_867Z-debug.log)

**Comment by ghaiklor** [comment]
I believe this is related to lodash package. The generator doesn't pin dependencies versions, so when it installs packages, lodash is installing with breaking version.

**Comment by ghost** [comment]
can you send me a working package json / a fix for that

**Comment by ghaiklor** [comment]
@LarsE343 You can install needed lodash version yourself via `npm install`. I can't send you the package.json with all the working dependencies.

**Comment by moda20** [comment]
So what is the necessary version of loadash ?

**Comment by binnyg** [comment]
@ghost, @moda20 Did you figure out the exact lodash version?

**Comment by moda20** [comment]
I just installed lodash latest via npm, it worked
