### ISSUE TITLE
Rethrow non-MySQL errors : Converting circular structure to JSON

### ISSUE THREAD

**Issue by mukulsoftwap** [ghaiklor/generator-sails-rest-api#360]
```
(node:16108) [DEP0095] DeprecationWarning: timers.enroll() is deprecated. Please use setTimeout instead.
(node:16108) [DEP0096] DeprecationWarning: timers.unenroll() is deprecated. Please use clearTimeout instead.
verbose: Lowering sails...
/home/mukuls/Desktop/dukanwale-web-app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:77
        throw err; // Rethrow non-MySQL errors
        ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at ServerResponse.res.json (/home/mukuls/Desktop/dukanwale-web-app/node_modules/@sailshq/express/lib/response.js:231:19)
    at ServerResponse.jsonx (/home/mukuls/Desktop/dukanwale-web-app/node_modules/sails/lib/hooks/responses/index.js:222:21)
    at Object.module.exports (/home/mukuls/Desktop/dukanwale-web-app/api/responses/badRequest.js:21:12)
    at /home/mukuls/Desktop/dukanwale-web-app/api/controllers/RolePermissionController.js:19:32
    at wrapper (/home/mukuls/Desktop/dukanwale-web-app/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/lib/waterline/utils/normalize.js:335:16)
    at error (/home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
    at _switch (/home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/node_modules/switchback/lib/factory.js:56:28)
    at /home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/lib/waterline/query/finders/basic.js:79:23
    at /home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/lib/waterline/query/finders/operations.js:72:21
    at wrapper (/home/mukuls/Desktop/dukanwale-web-app/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/lib/waterline/utils/normalize.js:335:16)
    at error (/home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
    at _switch (/home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/node_modules/switchback/lib/factory.js:56:28)
    at /home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/lib/waterline/adapter/dql.js:163:27
    at wrapper (/home/mukuls/Desktop/dukanwale-web-app/node_modules/lodash/index.js:3592:19)
    at applyInOriginalCtx (/home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/lib/waterline/utils/normalize.js:421:80)
    at wrappedCallback (/home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/lib/waterline/utils/normalize.js:335:16)
    at error (/home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/node_modules/switchback/lib/normalize.js:42:31)
    at _switch (/home/mukuls/Desktop/dukanwale-web-app/node_modules/waterline/node_modules/switchback/lib/factory.js:56:28)
    at sendBackError (/home/mukuls/Desktop/dukanwale-web-app/node_modules/sails-mysql/lib/connections/spawn.js:97:11)
    at Object.poolfully [as releaseConnection] (/home/mukuls/Desktop/dukanwale-web-app/node_modules/sails-mysql/lib/connections/release.js:28:12)
    at /home/mukuls/Desktop/dukanwale-web-app/node_modules/sails-mysql/lib/connections/spawn.js:90:37
    at Query._callback (/home/mukuls/Desktop/dukanwale-web-app/node_modules/sails-mysql/lib/adapter.js:917:20)
    at Query.Sequence.end (/home/mukuls/Desktop/dukanwale-web-app/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
```

**Working fine with sails disk but getting when using mysql. please help me**

**Comment by smitit173** [comment]
yeah , I am also facing the same issue
