### ISSUE TITLE
TypeError: Cannot read property 'package' of undefined

### ISSUE THREAD

**Issue by radiart** [ghaiklor/generator-sails-rest-api#98]
Windows 7, npm 3.3.4, node 4.1.1

yo sails-rest-api

C:\Users\Rafa┼é\AppData\Roaming\npm\node_modules\generator-sails-rest-api\generators\app\steps\install.js:31
          var missingDependencies = checkDependencies.missing(data.package, data.used).concat(missingAdapters);                                                                ^
TypeError: Cannot read property 'package' of undefined
    at null.<anonymous> (C:\Users\Rafa┼é\AppData\Roaming\npm\node_modules\generator-sails-rest-api\generators\app\steps\install.js:31:67)
    at C:\Users\Rafa┼é\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\index.js:101:21
    at C:\Users\Rafa┼é\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\async\lib\async.js:251:17
    at done (C:\Users\Rafa┼é\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\async\lib\async.js:126:15)
    at C:\Users\Rafa┼é\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\async\lib\async.js:32:16
    at C:\Users\Rafa┼é\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\async\lib\async.js:248:21
    at ReadFileContext.read [as callback] (C:\Users\Rafa┼é\AppData\Roaming\npm\node_modules\generator-sails-rest-api\node_modules\dependency-check\index.js:129:16)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)

**Comment by ghaiklor** [comment]
@radiart seems that you have some error in `dependency-check` module. I saw similar error on Windows platform before. Can you check it on another OS? Also I'm wondering if your username Rafa┼é is a root of problems.

**Comment by ghaiklor** [comment]
Fixed in the alpha-version and soon will be as a stable release.
