### ISSUE TITLE
Fresh install getting errors

### ISSUE THREAD

**Issue by combsco** [ghaiklor/generator-sails-rest-api#99]
Fresh install of Node, NPM
Fresh install of Yo, Sails, Sails-Rest-Api

Following Install/First run instructions... on main Github page.

````
/Users/crisopolis/Projects/schedulerapi/node_modules/passport-facebook-token/node_modules/passport-oauth2/lib/strategy.js:81
  if (!options.authorizationURL) { throw new TypeError('OAuth2Strategy requires a authorizationURL option'); }
                                   ^

TypeError: OAuth2Strategy requires a authorizationURL option
    at new OAuth2Strategy (/Users/crisopolis/Projects/schedulerapi/node_modules/passport-facebook-token/node_modules/passport-oauth2/lib/strategy.js:81:42)
    at Object.<anonymous> (/Users/crisopolis/Projects/schedulerapi/config/passport.js:156:14)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/crisopolis/Projects/schedulerapi/node_modules/sails/node_modules/include-all/index.js:129:29
    at Array.forEach (native)
    at requireAll (/Users/crisopolis/Projects/schedulerapi/node_modules/sails/node_modules/include-all/index.js:44:9)
    at buildDictionary (/Users/crisopolis/Projects/schedulerapi/node_modules/sails/node_modules/sails-build-dictionary/index.js:68:14)
    at Function.module.exports.aggregate (/Users/crisopolis/Projects/schedulerapi/node_modules/sails/node_modules/sails-build-dictionary/index.js:190:9)
    at Array.loadOtherConfigFiles (/Users/crisopolis/Projects/schedulerapi/node_modules/sails/lib/hooks/moduleloader/index.js:164:27)
    at /Users/crisopolis/Projects/schedulerapi/node_modules/sails/node_modules/async/lib/async.js:484:38
    at _each (/Users/crisopolis/Projects/schedulerapi/node_modules/sails/node_modules/async/lib/async.js:46:13)

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/Cellar/node/4.1.1/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! code ELIFECYCLE
npm ERR! schedulerapi@0.1.0 start: `node app.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the schedulerapi@0.1.0 start script 'node app.js'.
npm ERR! This is most likely a problem with the schedulerapi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls schedulerapi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/crisopolis/Projects/schedulerapi/npm-debug.log
````

**Comment by ghaiklor** [comment]
@combsco thanks for report. It's a known issue and I'm trying to fix that now.

The problem is in parsing dependencies and installing them. If someone's module is published with breaking changes, generator installs this one but not the working version.

Hotfix for this is generator `package.json` with predefined package versions and it will be available soon.

**Comment by ghaiklor** [comment]
@combsco just released new version. Try it out and give me your feedback, please.

**Comment by combsco** [comment]
Awesome... I see the update!

```
% npm outdated -g
Package                   Current  Wanted  Latest  Location
generator-sails-rest-api   0.10.5  0.10.6  0.10.6  /usr/local/lib > generator-sails-rest-api
npm                        2.14.4   3.3.4   3.3.4  /usr/local/lib > npm
```

Updated the package, removed and re-ran installation commands.
Sails lifts now!

```
Wed, 30 Sep 2015 15:29:45 GMT: verbose: All hooks were loaded successfully.
Wed, 30 Sep 2015 15:29:45 GMT: verbose: Starting app at /Users/crisopolis/Projects/schedulerapi...
Wed, 30 Sep 2015 15:29:45 GMT: verbose: Running the setup logic in `sails.config.bootstrap(cb)`...
Wed, 30 Sep 2015 15:29:45 GMT: info:
Wed, 30 Sep 2015 15:29:45 GMT: info:                .-..-.
Wed, 30 Sep 2015 15:29:45 GMT: info:
Wed, 30 Sep 2015 15:29:45 GMT: info:    Sails              <|    .-..-.
Wed, 30 Sep 2015 15:29:45 GMT: info:    v0.11.2             |\
Wed, 30 Sep 2015 15:29:45 GMT: info:                       /|.\
Wed, 30 Sep 2015 15:29:45 GMT: info:                      / || \
Wed, 30 Sep 2015 15:29:45 GMT: info:                    ,'  |'  \
Wed, 30 Sep 2015 15:29:45 GMT: info:                 .-'.-==|/_--'
Wed, 30 Sep 2015 15:29:45 GMT: info:                 `--'-------'
Wed, 30 Sep 2015 15:29:45 GMT: info:    __---___--___---___--___---___--___
Wed, 30 Sep 2015 15:29:45 GMT: info:  ____---___--___---___--___---___--___-__
Wed, 30 Sep 2015 15:29:45 GMT: info:
Wed, 30 Sep 2015 15:29:45 GMT: info: Server lifted in `/Users/crisopolis/Projects/schedulerapi`
Wed, 30 Sep 2015 15:29:45 GMT: info: To see your app, visit http://localhost:3000
Wed, 30 Sep 2015 15:29:45 GMT: info: To shut down Sails, press <CTRL> + C at any time.
Wed, 30 Sep 2015 15:29:45 GMT: debug: --------------------------------------------------------
Wed, 30 Sep 2015 15:29:45 GMT: debug: :: Wed Sep 30 2015 11:29:45 GMT-0400 (EDT)
Wed, 30 Sep 2015 15:29:45 GMT: debug: Environment : development
Wed, 30 Sep 2015 15:29:45 GMT: debug: Port        : 3000
Wed, 30 Sep 2015 15:29:45 GMT: debug: --------------------------------------------------------
```

Thanks for the fix @ghaiklor

**Comment by ghaiklor** [comment]
@combsco glad it helps you :+1:
